# Generated by Django 3.2 on 2022-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220616_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_lefty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
