# Generated by Django 3.2 on 2022-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_in_lefty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tuner_variation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
