# Generated by Django 3.2 on 2022-08-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tuner_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tuner_variation',
        ),
    ]
